openapi: 3.0.3
info:
  title: NutrifAI App API
  description: API defining the operations available in the NutrifAI App
  version: 1.0
paths:
  /login:
    post:
      x-amazon-apigateway-integration:
        $ref: "#/components/x-amazon-apigateway-integrations/lambda-authorizer"
  /register:
    post:
      x-amazon-apigateway-integration:
        $ref: "#/components/x-amazon-apigateway-integrations/lambda-authorizer"
  /logout:
    post:
      x-amazon-apigateway-integration:
        $ref: "#/components/x-amazon-apigateway-integrations/lambda-authorizer"
  /generateDiet:
    get:
      x-amazon-apigateway-integration:
        $ref: "#/components/x-amazon-apigateway-integrations/lambda-generate-diet"
      security:
        - session_authorizer: []
components:
  securitySchemes:
    session_authorizer:
      type: "apiKey"
      name: "Cookie"
      in: "header"
      x-amazon-apigateway-authorizer:
        identitySource: "$request.header.Cookie"
        authorizerUri: "arn:aws:apigateway:${aws_region}:lambda:path/2015-03-31/functions/${lambda_authorizer_invoke_arn}"
        authorizerCredentials: "${execution_role}"
        authorizerPayloadFormatVersion: "2.0"
        authorizerResultTtlInSeconds: 1
        type: "request"
        enableSimpleResponses: true
  x-amazon-apigateway-integrations:
    lambda-generate-diet:
      type: "aws_proxy"
      httpMethod: "POST"
      credentials: "${execution_role}"
      uri: "arn:aws:apigateway:${aws_region}:lambda:path/2015-03-31/functions/arn:aws:lambda:sa-east-1:${aws_account_id}:function:lambda-generate-diet/invocations"
      passthroughBehavior: "when_no_match"
      timeoutInMillis: 29000
      payloadFormatVersion: 2.0
    lambda-authorizer:
      type: "aws_proxy"
      httpMethod: "POST"
      credentials: "${execution_role}"
      uri: "arn:aws:apigateway:${aws_region}:lambda:path/2015-03-31/functions/arn:aws:lambda:sa-east-1:${aws_account_id}:function:lambda-authorizer/invocations"
      passthroughBehavior: "when_no_match"
      timeoutInMillis: 29000
      payloadFormatVersion: 2.0